// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://naghgnptrtjrjctmakxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hZ2hnbnB0cnRqcmpjdG1ha3h6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNTg3ODAsImV4cCI6MjA2MDczNDc4MH0.GEYl-sTi1VzhpLId_wZ0bx5GhgwyB7KrAhr-_td9Qto";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);